### ISSUE TITLE
Use futures

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/c3co#11]
Make use of "futures" :

* [ ]  to parallelize segmentation of different chromosomes in 'getSegmentData'
* [x] ~~to parallelize estimation of Z1 and Z2 in 'positiveFusedLasso'~~

**Comment by HenrikBengtsson** [comment]
As already shown (private email), it's not worth parallelizing Z1 and Z2 calculations.

**Comment by HenrikBengtsson** [comment]
Not sure if this is important enough. Closing for now.
