### ISSUE TITLE
FEEDBACK: getWeightMatrix()

### ISSUE THREAD

**Issue by HenrikBengtsson** [pneuvial/c3co#13]
Feedback / questions about:
```r
getWeightMatrix(prop.max, prob.min, nb.arch, nb.samp, sparse.coeff = 0.5, contam.coeff = 0.6, contam.max = 30)

#' Generate weight matrix
#'
#' @param prop.max An integer that is the maximim proportion for a present archetype
#' @param prob.min An integer that is the minimum proportion  for a present archetype
#' @param nb.arch  An interger that is the number of archetypes (number of columns)
#' @param nb.samp An interger that is the number of samples (number of rows)
#' @param contam.max An interger between 0 and 100 that controls the maximal level of contamination by normal cells
#' @param contam.coeff A numeric between 0 and 1 that control the contamination level
#' @param sparse.coeff A numeric between 0 and 1 that control the sparsity by rows
#' @return A matrix of weights (the sum of rows is equal to 1)
```
* TYPO: `prop.max` vs `prob.min`
* What's the range of the above two arguments?  (0,1,2,...,100)?
* Why integers and not fraction in [0,1]?  Same question for `contam.max`.
* Several spelling errors.
* A bit random spacing.

**Comment by pneuvial** [comment]
@mpierrejean can you fix this? In particular, rename prop.max to prob.max and make sure that prop.max,  prop.min, contam.max are in [0,1], not [0,100]? This would be consistent will the standard in acnr.

**Comment by pneuvial** [comment]
Also, it is unclear from the documentation what the difference between contam.max and contam.coeff is. Please clarify in the doc that the contamination is drawn from a binomial distribution with parameters size=contam.max (or 100*contam.max after fixing this issue) and prob=contam.coeff.

**Comment by HenrikBengtsson** [comment]
Is this issue moot?  I don't see a `getWeightMatrix()` in `intercept` branch.

**Comment by HenrikBengtsson** [comment]
Flagging as 'expired'.
