### ISSUE TITLE
BUG: cat(str(x))

### ISSUE THREAD

**Issue by HenrikBengtsson** [pneuvial/c3co#15]
FYI, using `cat(str(...))` is most likely a bug, e.g. from https://github.com/pneuvial/c3co/blob/master/R/AllGenerics.R#L22-L26:
```r
        cat("Subclones\n")
        cat(str(this@S), "\n")
        cat("Weights\n")
        cat(str(this@W), "\n")
        cat("Estimates\n")
        cat(str(this@E), "\n")
        [...]
        cat("param\n")
        cat(str(this@param), "\n")
```

**Comment by pneuvial** [comment]
Fixed in efa5200e8d7db4b4a0b31943aeb865624e8d29b0

Also renamed the showPosFused and showC3co methods to 'show'.
