### ISSUE TITLE
Avoid saving segmented data to disk

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/c3co#20]
Now that the c3co function can take segmented data as input, we should modify the PSCBS and facets wrappers so that they don't save segmented data to file but rather return it (it is light enough by definition).   The examples and the PSCBS vignette should be updated accordingly.

**Comment by HenrikBengtsson** [comment]
* [x] `PSCBSwrapper()`-  fixed in commit 0adcf07
* [ ] `Facetswrapper()`
