### ISSUE TITLE
TASK: Unit tests for `get.W()`, `get.Z()`, and `positiveFusedLasso()`

### ISSUE THREAD

**Issue by HenrikBengtsson** [pneuvial/c3co#42]
Write unit tests for `get.W()`, `get.Z()`, and `positiveFusedLasso()`:

* [x] Produce simulated data, e.g. `getToyData()`
* [x] Tests for `get.W()`:
  - [x] Number of signal dimension: One and two-dimensional data, e.g. total CN and (C1,C2). 
  - [x] Number of subclones: K=1. Cannot be done before #52 is fixed
  - [x] Number of subclones: K=2,3
  - [x] Number of samples: n=1. Cannot be done before #52 is fixed
  - [x] Number of samples: n=2,3
  - [x] Number of segments: J=1,2,8
* [x] Tests for `get.Zt()`:
  - [x] Number of signal dimension: One and two-dimensional data, e.g. total CN and (C1,C2). 
  - [x] Number of subclones: K=1,2,3
  - [x] Number of segments: J=1,2,8
  - [x] Number of samples: n=1,2,3
* [x] Tests for `initializeZt()`
  - DECISION 2019-02-20: Let's skip this because at the end of the day all it does is calling `cutree(hc, k=K)` + `rowMeans()`. The unit tests of `positiveFusedLasso()` will cover this anyway.
* [x] Tests for `positiveFusedLasso()`
  - [x] Number of signal dimension: One and two-dimensional data, e.g. total CN and (C1,C2). 
  - [x] Number of subclones: K=1,2,3
  - [x] Number of segments: J=1,2,8
  - [x] Number of samples: n=1,2,3

**Comment by pneuvial** [comment]
```
p <- 100 # length of locus-level data
J  <- 5  
K <- 2
n <- 3
dat <- getToyData(n = n, len = p, nbClones = K, nbBkps = J + 1 , eps=0)  ## noiseless
```
