### ISSUE TITLE
TASK: Rename variable `Z` to `Zt` where it is actually `t(Z)`

### ISSUE THREAD

**Issue by HenrikBengtsson** [pneuvial/c3co#43]

**Comment by pneuvial** [comment]
Some inconsistencies:

- `positiveFusedLasso` takes a K -by- J matrix Z and returns a J -by- K matrix
- the dimensions of Z are documented as L -by- p

**Comment by HenrikBengtsson** [comment]
* `get.W()` takes `t(Z)` as input - not `Z`.
* `get.Z()` seems to return `t(Z)`

**Comment by HenrikBengtsson** [comment]
* [ ] It looks like `initializeZ()` returns `t(Z)` => renamed `initializeZt()`
