### ISSUE TITLE
CONSISTENCY: lambda penalty is not on the expected scale in get.Zt

### ISSUE THREAD

**Issue by jchiquet** [pneuvial/c3co#57]
The glmnet is solving 1/2 RSS/nobs + λ*penalty. We use it to solve something like RSS + λ*penalty. So to be consistent with the value of lambda provided by the user, we should divide by a factor (2 * nobs), which is (2 * n * J) in the case at hand.

**Comment by HenrikBengtsson** [comment]
Note to ourselves: I just wanted make sure we're not adjusting `lambda` prior to calling `get.Zt()`; I just checked `positiveFusedLasso()` and I can confirm that `lambda` is not changed within that algorithm.
