### ISSUE TITLE
NOTE on how rank deficiency in Z is handled in get.W

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/c3co#63]
In `get.W`we are using least squares under equality/inequality constraints to solving Y = ZW+E for W. Solving the unconstrained version in W  gives (the equations below are clikable!)

<a href="https://www.codecogs.com/eqnedit.php?latex=W&space;=&space;YZ^t(ZZ^t)^{-1}" target="_blank"><img src="https://latex.codecogs.com/png.latex?W&space;=&space;YZ^t(ZZ^t)^{-1}" title="W = YZ^t(ZZ^t)^{-1}" /></a>

This is what is done in `lsei(..., type = 1)`. When Z is not full row rank (e.g. because K > J), we can instead solve a ridge-penalized version:

<a href="https://www.codecogs.com/eqnedit.php?latex=W&space;=&space;YZ^t(ZZ^t+\epsilon I)^{-1}" target="_blank"><img src="https://latex.codecogs.com/png.latex?W&space;=&space;YZ^t(ZZ^t+\epsilon&space;I)^{-1}" title="W = YZ^t(ZZ^t+\epsilon I )^{-1}" /></a>

This is what is done in `lsei(..., type = 2)`

DECISION (for now): For interpretability reasons we make the non-penalized version the default, and add a sanity check that K (subclones) is less than J (segments).  

NOTE: J is not the *true* number of segments but the *estimated* one after segmentation. The issue of possible rank deficiency in Z is related to over/under-segmentation.

**Comment by jchiquet** [comment]
Regarding testing if K > J, we cannot do this straightforwardly in get.W (see #64 for details).

I suggest to do this in positiveFusedLasso.

**Comment by pneuvial** [comment]
A sanity check has been added in get.W to address this point (cf #64)
